qiandao:
  1:
    cmd: give {Player} 7 10
  2:
    cmd: give {Player} 7 10
  3:
    cmd: give {Player} 7 10
  4:
    cmd: give {Player} 7 10
  5:
    cmd: give {Player} 7 10
  6:
    cmd: give {Player} 7 10
  7:
    cmd: give {Player} 7 10
  8:
    cmd: give {Player} 7 10
  9:
    cmd: give {Player} 7 10
  10:
    cmd: give {Player} 7 10
  11:
    cmd: give {Player} 7 10
  12:
    cmd: give {Player} 7 10
  13:
    cmd: give {Player} 7 10
  14:
    cmd: give {Player} 7 10
  15:
    cmd: give {Player} 7 10
  16:
    cmd: give {Player} 7 10
  17:
    cmd: give {Player} 7 10
  18:
    cmd: give {Player} 7 10
  19:
    cmd: give {Player} 7 10
  20:
    cmd: give {Player} 7 10
  21:
    cmd: give {Player} 7 10
  22:
    cmd: give {Player} 7 10
  23:
    cmd: give {Player} 7 10
  24:
    cmd: give {Player} 7 10
  25:
    cmd: give {Player} 7 10
  26:
    cmd: give {Player} 7 10
  27:
    cmd: give {Player} 7 10
  28:
    cmd: give {Player} 7 10
  29:
    cmd: give {Player} 7 10
  30:
    cmd: give {Player} 7 10
  31:
    cmd: give {Player} 7 10
  32:
    cmd: give {Player} 7 10